# Generated by Django 4.1.7 on 2023-04-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=150)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_pedido', models.DateTimeField()),
                ('tipo_envio', models.CharField(choices=[('EST', 'Estándar'), ('URG', 'Urgente')], max_length=3)),
                ('agencia_transporte', models.CharField(choices=[('COR', 'Correos'), ('SEU', 'Seur'), ('DHL', 'DHL')], max_length=3)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_almacenes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_posicion', models.CharField(choices=[('PIC', 'Picking'), ('STO', 'Stock')], max_length=3)),
                ('capacidad', models.PositiveIntegerField()),
                ('unidades_ocupadas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=20)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad_stock', models.PositiveIntegerField()),
                ('cantidad_minima_reaprovisionamiento', models.PositiveIntegerField()),
                ('peso_por_unidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_almacenada', models.PositiveIntegerField()),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_almacenes.posicion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_almacenes.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_almacenes.proveedor'),
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_almacenes.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_almacenes.producto')),
            ],
        ),
    ]
