# Generated by Django 4.1.7 on 2023-04-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_almacenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre_producto',
        ),
    ]
