# Generated by Django 4.1.7 on 2023-04-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_almacenes', '0002_alter_posicion_unidades_ocupadas_and_more'),
        ('gestion_almacenes', '0002_alter_producto_cantidad_stock_and_more'),
    ]

    operations = [
    ]
