# Generated by Django 4.1.7 on 2023-04-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_almacenes', '0002_remove_producto_nombre_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_stock',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_por_unidad',
            field=models.FloatField(null=True),
        ),
    ]
