# Generated by Django 4.1.7 on 2023-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_almacenes', '0003_alter_producto_cantidad_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_por_unidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
