# Generated by Django 4.1.7 on 2023-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_almacenes', '0004_alter_posicion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
