# Generated by Django 4.1.7 on 2023-04-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_almacenes', '0006_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoposicion',
            name='cantidad_almacenada',
        ),
    ]
