# Generated by Django 4.1.7 on 2023-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_almacenes', '0008_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='albaran',
            field=models.FileField(blank=True, null=True, upload_to='ruta/de/almacenamiento/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='etiqueta',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
